#!/bin/bash
JAR=$1
ROOT_DIR=$PWD

mkdir -p $ROOT_DIR/work
jdeps --generate-module-info work in/$JAR
ls -l work
MODULE=$(ls -l work | awk '{print $NF}' | grep -v 0)

# copy original jar into place
mkdir -p $ROOT_DIR/out
cp $ROOT_DIR/in/$JAR $ROOT_DIR/out/$MODULE.jar

# extract original jar
mkdir $ROOT_DIR/classes
cd $ROOT_DIR/classes
jar xf $ROOT_DIR/in/$JAR

# compile module-info.java (generated by gen.sh)
cd $ROOT_DIR/work/$MODULE
javac -p $MODULE -d $ROOT_DIR/classes module-info.java

# update output jar
jar uf $ROOT_DIR/out/$MODULE.jar -C $ROOT_DIR/classes module-info.class

cd $ROOT_DIR

mv $ROOT_DIR/out/$MODULE.jar $ROOT_DIR/../$JAR

rm -rf $ROOT_DIR/work
rm -rf $ROOT_DIR/out
rm -rf $ROOT_DIR/classes

echo "Ready."